---
- name: Upgrade packages
  apt: upgrade=yes
  tags:
    - packages

# /etc/default/rcS exists in Ubunut 16.04 but not in 17.04
- name: Check if /etc/default/rcS exists
  stat: path=/etc/default/rcS
  register: rcS_stat

- name: Enable fsckfix during boot
  lineinfile:
    dest: /etc/default/rcS
    regexp: '^FSCKFIX='
    line: "FSCKFIX=yes"
    backup: yes
  when: rcS_stat.stat.exists == True
  tags:
    - rcS

- name: Remove /tmp/* files during boot
  lineinfile:
    dest: /etc/default/rcS
    regexp: '^TMPTIME='
    line: "TMPTIME=0"
    backup: yes
  when: rcS_stat.stat.exists == True
  tags:
    - rcS

- name: Enable sysstat (sar)
  lineinfile:
    dest: /etc/default/sysstat
    regexp: '^ENABLED='
    line: 'ENABLED="true"'
    backup: yes
  tags:
    - sysstat

- name: Change shell to /bin/bash for new users (/etc/default/useradd)
  lineinfile:
    dest: /etc/default/useradd
    regexp: '^SHELL='
    line: 'SHELL=/bin/bash'
    backup: yes
  tags:
    - sysstat

- name: Change shell to /bin/bash for new users (/etc/default/useradd)
  lineinfile:
    dest: /etc/tmpreaper.conf
    regexp: '^SHOWWARNING='
    line: 'SHOWWARNING=false'
    backup: yes
  tags:
    - tmpreaper

- name: Modify Unattended upgrade settings
  replace:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: '^//Unattended-Upgrade::Mail "root";', replace: 'Unattended-Upgrade::Mail "root";' }
    - { regexp: '^//Unattended-Upgrade::Remove-Unused-Dependencies "false";', replace: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";' }
  tags:
    - unattended-upgrades

- name: Autoremove unused packages
  command: apt-get -y autoremove
  register: autoremove_output
  changed_when: "'The following packages will be REMOVED' in autoremove_output.stdout"

- name: Disable periodic activities of apt
  copy:
    src: etc/apt/apt.conf.d/10disable-periodic
    dest: /etc/apt/apt.conf.d/10disable-periodic
