---

root_password: vagrant

skel_copy_users:
  - /home/ubuntu
  - /home/centos
  - /home/vagrant
  - /root

common_packages:
  - acpid
  - atop
  - bash-completion
  - byobu
  - cloud-init
  - curl
  - dstat
  - ethtool
  - haveged
  - htop
  - iftop
  - iotop
  - lftp
  - logrotate
  - logwatch
  - lshw
  - lsof
  - man
  - mc
  - mlocate
  - mutt
  - nmap
  - ntp
  - ntpdate
  - openssh-server
  - parted
  - postfix
  - rsync
  - screen
  - strace
  - sysstat
  - tcpdump
  - telnet
  - traceroute

enable_boot_services:
  - acpid
  - atop
  - haveged
  - serial-getty@ttyS1.service
