version: 1
update_configs:
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    default_assignees:
      - "ruzickap"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
