name: periodic-markdown-links-check

on:
  schedule:
    - cron: '8 8 * * 1'
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/periodic-markdown-links-check.yml

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: ruzickap/action-my-markdown-link-checker@v1
        with:
          exclude: |
            CHANGELOG.md
