name: periodic-markdown-links-check

on:
  schedule:
    - cron: '8 8 * * 1'
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/periodic-markdown-links-check.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/periodic-markdown-links-check.yml

jobs:
  markdown-link-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: gaurav-nelson/github-action-markdown-link-check@0.6.0
        with:
          config-file: '.mlc_config.json'
