---
name: stale

on:
  schedule:
    - cron: "30 1 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          close-issue-message: |
            This issue has not seen any activity since it was marked stale.
            Closing.
          close-pr-message: |
            This pull request has not seen any activity since it was marked stale.
            Closing.
          exempt-issue-labels: good-first-issue,need-help,no-stale,pinned,security
          exempt-pr-labels: "autorelease: pending,good-first-issue,need-help,no-stale,pinned,security"
          stale-issue-label: stale
          stale-issue-message: |
            This issue is stale because it has been open 60 days with no activity.
            Remove stale label or comment or this will be closed in 7 days
          stale-pr-label: stale
          stale-pr-message: |
            This PR is stale because it has been open 60 days with no activity.
            Remove stale label or comment or this will be closed in 7 days.
